import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[window]
opacity =0.9

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 250
lines = 56

[window.position]
x = 0
y = 0 

[cursor]
style = { shape = "Beam", blinking = "On" }

